{
 "title": "iDRAC",
 "tags": [ "SERVIDORESTJRR" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Grupo",
    "query": {}
   },
   {
    "name": "host",
    "label": "Servidor",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperatura IDRAC",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "application": { "filter": "Temperature" },
     "functions": [
      {
       "$$hashKey": "object:336",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$__zbx_item" ],
       "text": "setAlias($__zbx_item)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Temp:/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Raid",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "Virtual disks" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "functions": [
      {
       "$$hashKey": "object:475",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$__zbx_item" ],
       "text": "setAlias($__zbx_item)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/battery status/" },
     "itemTag": { "filter": "component: array" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "application": { "filter": "Virtual disks" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "functions": [
      {
       "$$hashKey": "object:477",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$__zbx_item" ],
       "text": "setAlias($__zbx_item)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/controller status/" },
     "itemTag": { "filter": "component: array" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "Virtual disks" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "functions": [
      {
       "$$hashKey": "object:225",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "PowerEdge R450: ",
        " "
       ],
       "text": "replaceAlias(PowerEdge R450: ,  )"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Fan speed/" },
     "itemTag": { "filter": "component: fan" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Fan status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "Virtual disks" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "functions": [
      {
       "$$hashKey": "object:362",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$__zbx_item" ],
       "text": "setAlias($__zbx_item)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Fan status/" },
     "itemTag": { "filter": "component: fan" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Physical disk status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Filesystem C:" },
     "functions": [
      {
       "$$hashKey": "object:588",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$__zbx_item" ],
       "text": "setAlias($__zbx_item)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Physical disk status/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "S.M.A.R.T. status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "Physical disks" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "functions": [
      {
       "$$hashKey": "object:644",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$__zbx_item" ],
       "text": "setAlias($__zbx_item)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/S.M.A.R.T. status/" },
     "itemTag": { "filter": "component: disk" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Disk size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "Physical disks" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "functions": [
      {
       "$$hashKey": "object:43",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$__zbx_item" ],
       "text": "setAlias($__zbx_item)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Disk size/" },
     "itemTag": { "filter": "component: disk" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Read policy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "Physical disks" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Read policy/" },
     "itemTag": { "filter": "component: disk" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Layout type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "Physical disks" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Layout type/" },
     "itemTag": { "filter": "component: disk" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Controller battery status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "Physical disks" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Battery 1: Disk array cache controller battery status"
     },
     "itemTag": { "filter": "component: disk" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Overall system health status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Disk 1 C:" },
     "functions": [
      {
       "$$hashKey": "object:1024",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "PowerEdge R450: ",
        " "
       ],
       "text": "replaceAlias(PowerEdge R450: ,  )"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Overall system health status" },
     "itemTag": { "filter": "component: system" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Current state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "Physical disks" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Current state/" },
     "itemTag": { "filter": "component: disk" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}